export { default as MainLayout } from "./layout/"
export { default as Header } from "./header"
export { default as Cards } from "./cards/"
export { default as DetailCard } from "./detailCard"
export { default as Pagination } from "./pagination"
export { default as Footer } from "./footer"
